// Generated by scripts/generate-cloud-api-operations.mjs from contracts/laravel-cloud-openapi.json.
// Do not edit by hand; run `bun run api:types`.
import type { WriteOperation } from "./operation-types";

export const WRITE_OPERATIONS: readonly WriteOperation[] = [
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "The source control provider. This parameter will be required starting March 9, 2026.",
          "name": "source_control_provider_type",
          "nullable": false,
          "path": [
            "source_control_provider_type"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "github",
            "gitlab",
            "gitlab_self_hosted",
            "bitbucket"
          ]
        },
        {
          "name": "repository",
          "nullable": false,
          "path": [
            "repository"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[\\p{Latin}0-9 _.,'\\-&()!#+:@]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "region",
          "nullable": false,
          "path": [
            "region"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "us-east-2",
            "us-east-1",
            "ca-central-1",
            "eu-central-1",
            "eu-west-1",
            "eu-west-2",
            "me-central-1",
            "ap-southeast-1",
            "ap-southeast-2",
            "ap-northeast-1"
          ]
        },
        {
          "maxLength": 255,
          "name": "root_directory",
          "nullable": true,
          "path": [
            "root_directory"
          ],
          "pattern": "^[a-zA-Z0-9][-a-zA-Z0-9_.]*(?:\\/[a-zA-Z0-9][-a-zA-Z0-9_.]*)*$",
          "required": false,
          "kind": "string"
        },
        {
          "description": "The identifier of a dedicated cluster to deploy to. Only fill it if your organization has a dedicated cluster and you want to use it for this application.",
          "name": "cluster_id",
          "nullable": true,
          "path": [
            "cluster_id"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new application.",
    "method": "POST",
    "operationId": "public.applications.store",
    "params": [],
    "path": "/applications",
    "query": [],
    "summary": "Create application",
    "tag": "Applications"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "The source control provider. This parameter will be required starting March 9, 2026.",
          "name": "source_control_provider_type",
          "nullable": false,
          "path": [
            "source_control_provider_type"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "github",
            "gitlab",
            "gitlab_self_hosted",
            "bitbucket"
          ]
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[\\p{Latin}0-9 _.'-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "minLength": 3,
          "name": "slug",
          "nullable": false,
          "path": [
            "slug"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "default_environment_id",
          "nullable": false,
          "path": [
            "default_environment_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "repository",
          "nullable": false,
          "path": [
            "repository"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "slack_channel",
          "nullable": true,
          "path": [
            "slack_channel"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Update an application.",
    "method": "PATCH",
    "operationId": "public.applications.update",
    "params": [
      "application"
    ],
    "path": "/applications/{application}",
    "query": [],
    "summary": "Update application",
    "tag": "Applications"
  },
  {
    "body": null,
    "description": "Delete an application and all of its environments.",
    "method": "DELETE",
    "operationId": "public.applications.destroy",
    "params": [
      "application"
    ],
    "path": "/applications/{application}",
    "query": [],
    "summary": "Delete application",
    "tag": "Applications"
  },
  {
    "body": {
      "contentType": "multipart",
      "fields": [
        {
          "description": "Maximum file size: 3072 kilobytes.",
          "format": "binary",
          "name": "avatar",
          "nullable": false,
          "path": [
            "avatar"
          ],
          "required": true,
          "kind": "file"
        }
      ]
    },
    "description": "Upload or replace the avatar for an application.",
    "method": "POST",
    "operationId": "public.applications.avatar.store",
    "params": [
      "application"
    ],
    "path": "/applications/{application}/avatar",
    "query": [],
    "summary": "Upload application avatar",
    "tag": "Applications"
  },
  {
    "body": null,
    "description": "Remove the avatar from an application.",
    "method": "DELETE",
    "operationId": "public.applications.avatar.destroy",
    "params": [
      "application"
    ],
    "path": "/applications/{application}/avatar",
    "query": [],
    "summary": "Delete application avatar",
    "tag": "Applications"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "worker",
            "custom"
          ]
        },
        {
          "max": 10,
          "min": 1,
          "name": "processes",
          "nullable": false,
          "path": [
            "processes"
          ],
          "required": true,
          "kind": "integer"
        },
        {
          "description": "Custom command to run. Required when type is 'custom'. Not applicable for 'worker' type.",
          "name": "command",
          "nullable": false,
          "path": [
            "command"
          ],
          "required": false,
          "example": "php artisan my:command",
          "kind": "string"
        },
        {
          "description": "The queue connection name. Only applicable for 'worker' type background processes.",
          "name": "config.connection",
          "nullable": false,
          "path": [
            "config",
            "connection"
          ],
          "required": false,
          "example": "redis",
          "kind": "string"
        },
        {
          "description": "The queue name(s) to process. Can be comma-separated for multiple queues. Only applicable for 'worker' type background processes.",
          "name": "config.queue",
          "nullable": false,
          "path": [
            "config",
            "queue"
          ],
          "required": false,
          "example": "default,emails",
          "kind": "string"
        },
        {
          "description": "Number of times a job should be attempted. Only applicable for 'worker' type background processes.",
          "name": "config.tries",
          "nullable": false,
          "path": [
            "config",
            "tries"
          ],
          "required": false,
          "example": "3",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to wait before retrying a failed job. Only applicable for 'worker' type background processes.",
          "name": "config.backoff",
          "nullable": false,
          "path": [
            "config",
            "backoff"
          ],
          "required": false,
          "example": "30",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to sleep when no jobs are available. Only applicable for 'worker' type background processes.",
          "name": "config.sleep",
          "nullable": false,
          "path": [
            "config",
            "sleep"
          ],
          "required": false,
          "example": "3",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to rest between jobs. Only applicable for 'worker' type background processes.",
          "name": "config.rest",
          "nullable": false,
          "path": [
            "config",
            "rest"
          ],
          "required": false,
          "example": "0",
          "kind": "integer"
        },
        {
          "description": "Number of seconds a job can run before timing out. Only applicable for 'worker' type background processes.",
          "name": "config.timeout",
          "nullable": false,
          "path": [
            "config",
            "timeout"
          ],
          "required": false,
          "example": "60",
          "kind": "integer"
        },
        {
          "description": "Force the worker to run even in maintenance mode. Only applicable for 'worker' type background processes.",
          "name": "config.force",
          "nullable": false,
          "path": [
            "config",
            "force"
          ],
          "required": false,
          "kind": "boolean"
        }
      ]
    },
    "description": "Create a new background process for an instance.",
    "method": "POST",
    "operationId": "public.instances.background-processes.store",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/background-processes",
    "query": [],
    "summary": "Create background process",
    "tag": "Background Processes"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "worker",
            "custom"
          ]
        },
        {
          "max": 10,
          "min": 1,
          "name": "processes",
          "nullable": false,
          "path": [
            "processes"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "description": "Custom command to run. Required when type is 'custom'. Not applicable for 'worker' type.",
          "name": "command",
          "nullable": false,
          "path": [
            "command"
          ],
          "required": false,
          "example": "php artisan my:command",
          "kind": "string"
        },
        {
          "description": "The queue connection name. Only applicable for 'worker' type background processes.",
          "name": "config.connection",
          "nullable": false,
          "path": [
            "config",
            "connection"
          ],
          "required": false,
          "example": "redis",
          "kind": "string"
        },
        {
          "description": "The queue name(s) to process. Can be comma-separated for multiple queues. Only applicable for 'worker' type background processes.",
          "name": "config.queue",
          "nullable": false,
          "path": [
            "config",
            "queue"
          ],
          "required": false,
          "example": "default,emails",
          "kind": "string"
        },
        {
          "description": "Number of times a job should be attempted. Only applicable for 'worker' type background processes.",
          "name": "config.tries",
          "nullable": false,
          "path": [
            "config",
            "tries"
          ],
          "required": false,
          "example": "3",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to wait before retrying a failed job. Only applicable for 'worker' type background processes.",
          "name": "config.backoff",
          "nullable": false,
          "path": [
            "config",
            "backoff"
          ],
          "required": false,
          "example": "30",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to sleep when no jobs are available. Only applicable for 'worker' type background processes.",
          "name": "config.sleep",
          "nullable": false,
          "path": [
            "config",
            "sleep"
          ],
          "required": false,
          "example": "3",
          "kind": "integer"
        },
        {
          "description": "Number of seconds to rest between jobs. Only applicable for 'worker' type background processes.",
          "name": "config.rest",
          "nullable": false,
          "path": [
            "config",
            "rest"
          ],
          "required": false,
          "example": "0",
          "kind": "integer"
        },
        {
          "description": "Number of seconds a job can run before timing out. Only applicable for 'worker' type background processes.",
          "name": "config.timeout",
          "nullable": false,
          "path": [
            "config",
            "timeout"
          ],
          "required": false,
          "example": "60",
          "kind": "integer"
        },
        {
          "description": "Force the worker to run even in maintenance mode. Only applicable for 'worker' type background processes.",
          "name": "config.force",
          "nullable": false,
          "path": [
            "config",
            "force"
          ],
          "required": false,
          "kind": "boolean"
        }
      ]
    },
    "description": "Update a background process.",
    "method": "PATCH",
    "operationId": "public.background-processes.update",
    "params": [
      "backgroundProcess"
    ],
    "path": "/background-processes/{backgroundProcess}",
    "query": [],
    "summary": "Update background process",
    "tag": "Background Processes"
  },
  {
    "body": null,
    "description": "Delete a background process.",
    "method": "DELETE",
    "operationId": "public.background-processes.destroy",
    "params": [
      "backgroundProcess"
    ],
    "path": "/background-processes/{backgroundProcess}",
    "query": [],
    "summary": "Delete background process",
    "tag": "Background Processes"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "name": "permission",
          "nullable": false,
          "path": [
            "permission"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "read_write",
            "read_only"
          ]
        }
      ]
    },
    "description": "Create a new key for an object storage bucket.",
    "method": "POST",
    "operationId": "public.buckets.keys.store",
    "params": [
      "filesystem"
    ],
    "path": "/buckets/{filesystem}/keys",
    "query": [],
    "summary": "Create object storage key",
    "tag": "Bucket Keys"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        }
      ]
    },
    "description": "Update an object storage key.",
    "method": "PATCH",
    "operationId": "public.bucket-keys.update",
    "params": [
      "filesystemKey"
    ],
    "path": "/bucket-keys/{filesystemKey}",
    "query": [],
    "summary": "Update object storage key",
    "tag": "Bucket Keys"
  },
  {
    "body": null,
    "description": "Delete an object storage key.",
    "method": "DELETE",
    "operationId": "public.bucket-keys.destroy",
    "params": [
      "filesystemKey"
    ],
    "path": "/bucket-keys/{filesystemKey}",
    "query": [],
    "summary": "Delete object storage key",
    "tag": "Bucket Keys"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "upstash_redis",
            "laravel_valkey",
            "aws_elasticache_redis",
            "aws_elasticache_valkey"
          ]
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "region",
          "nullable": false,
          "path": [
            "region"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "us-east-2",
            "us-east-1",
            "ca-central-1",
            "eu-central-1",
            "eu-west-1",
            "eu-west-2",
            "me-central-1",
            "ap-southeast-1",
            "ap-southeast-2",
            "ap-northeast-1"
          ]
        },
        {
          "name": "size",
          "nullable": false,
          "path": [
            "size"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "250mb",
            "1gb",
            "2.5gb",
            "5gb",
            "12gb",
            "50gb",
            "100gb",
            "500gb",
            "valkey-flex-250mb",
            "valkey-flex-1gb",
            "valkey-flex-2.5gb",
            "valkey-pro.250mb",
            "valkey-pro.1gb",
            "valkey-pro.2.5gb",
            "valkey-pro.5gb",
            "valkey-pro.12gb",
            "valkey-pro.25gb",
            "valkey-pro.50gb",
            "elasticache.cache.r7g.large",
            "elasticache.cache.r7g.xlarge",
            "elasticache.cache.r7g.2xlarge",
            "elasticache.cache.r7g.4xlarge",
            "elasticache.cache.r7g.8xlarge",
            "elasticache.cache.r7g.12xlarge",
            "elasticache.cache.r7g.16xlarge",
            "elasticache.cache.c7gn.large",
            "elasticache.cache.c7gn.xlarge",
            "elasticache.cache.c7gn.2xlarge",
            "elasticache.cache.c7gn.4xlarge",
            "elasticache.cache.c7gn.8xlarge",
            "elasticache.cache.c7gn.12xlarge",
            "elasticache.cache.c7gn.16xlarge",
            "elasticache.cache.t4g.micro",
            "elasticache.cache.t4g.small",
            "elasticache.cache.t4g.medium",
            "elasticache.cache.m7g.large",
            "elasticache.cache.m7g.xlarge",
            "elasticache.cache.m7g.2xlarge",
            "elasticache.cache.m7g.4xlarge",
            "elasticache.cache.m7g.8xlarge",
            "elasticache.cache.m7g.12xlarge",
            "elasticache.cache.m7g.16xlarge",
            "elasticache.cache.m8g.large",
            "elasticache.cache.m8g.xlarge",
            "elasticache.cache.m8g.2xlarge",
            "elasticache.cache.m8g.4xlarge",
            "elasticache.cache.m8g.8xlarge",
            "elasticache.cache.m8g.12xlarge",
            "elasticache.cache.m8g.16xlarge",
            "elasticache.cache.r8g.large",
            "elasticache.cache.r8g.xlarge",
            "elasticache.cache.r8g.2xlarge",
            "elasticache.cache.r8g.4xlarge",
            "elasticache.cache.r8g.8xlarge",
            "elasticache.cache.r8g.12xlarge",
            "elasticache.cache.r8g.16xlarge",
            "elasticache.cache.c8gn.large",
            "elasticache.cache.c8gn.xlarge",
            "elasticache.cache.c8gn.2xlarge",
            "elasticache.cache.c8gn.4xlarge",
            "elasticache.cache.c8gn.8xlarge",
            "elasticache.cache.c8gn.12xlarge",
            "elasticache.cache.c8gn.16xlarge"
          ]
        },
        {
          "name": "auto_upgrade_enabled",
          "nullable": false,
          "path": [
            "auto_upgrade_enabled"
          ],
          "required": true,
          "kind": "boolean"
        },
        {
          "name": "is_public",
          "nullable": false,
          "path": [
            "is_public"
          ],
          "required": true,
          "kind": "boolean"
        },
        {
          "name": "cluster_id",
          "nullable": true,
          "path": [
            "cluster_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "description": "Only available for Valkey. If not provided, allkeys-lru will be used.",
          "name": "eviction_policy",
          "nullable": true,
          "path": [
            "eviction_policy"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "allkeys-lru",
            "noeviction",
            "volatile-lru",
            "allkeys-random",
            "volatile-random",
            "volatile-ttl",
            "allkeys-lfu",
            "volatile-lfu"
          ]
        },
        {
          "name": "uses_hibernation",
          "nullable": false,
          "path": [
            "uses_hibernation"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 60,
          "min": 1,
          "name": "hibernation_timeout",
          "nullable": true,
          "path": [
            "hibernation_timeout"
          ],
          "required": false,
          "kind": "integer"
        }
      ]
    },
    "description": "Create a new cache.",
    "method": "POST",
    "operationId": "public.caches.store",
    "params": [],
    "path": "/caches",
    "query": [],
    "summary": "Create cache",
    "tag": "Caches"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "name": "size",
          "nullable": false,
          "path": [
            "size"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "250mb",
            "1gb",
            "2.5gb",
            "5gb",
            "12gb",
            "50gb",
            "100gb",
            "500gb",
            "valkey-flex-250mb",
            "valkey-flex-1gb",
            "valkey-flex-2.5gb",
            "valkey-pro.250mb",
            "valkey-pro.1gb",
            "valkey-pro.2.5gb",
            "valkey-pro.5gb",
            "valkey-pro.12gb",
            "valkey-pro.25gb",
            "valkey-pro.50gb",
            "elasticache.cache.r7g.large",
            "elasticache.cache.r7g.xlarge",
            "elasticache.cache.r7g.2xlarge",
            "elasticache.cache.r7g.4xlarge",
            "elasticache.cache.r7g.8xlarge",
            "elasticache.cache.r7g.12xlarge",
            "elasticache.cache.r7g.16xlarge",
            "elasticache.cache.c7gn.large",
            "elasticache.cache.c7gn.xlarge",
            "elasticache.cache.c7gn.2xlarge",
            "elasticache.cache.c7gn.4xlarge",
            "elasticache.cache.c7gn.8xlarge",
            "elasticache.cache.c7gn.12xlarge",
            "elasticache.cache.c7gn.16xlarge",
            "elasticache.cache.t4g.micro",
            "elasticache.cache.t4g.small",
            "elasticache.cache.t4g.medium",
            "elasticache.cache.m7g.large",
            "elasticache.cache.m7g.xlarge",
            "elasticache.cache.m7g.2xlarge",
            "elasticache.cache.m7g.4xlarge",
            "elasticache.cache.m7g.8xlarge",
            "elasticache.cache.m7g.12xlarge",
            "elasticache.cache.m7g.16xlarge",
            "elasticache.cache.m8g.large",
            "elasticache.cache.m8g.xlarge",
            "elasticache.cache.m8g.2xlarge",
            "elasticache.cache.m8g.4xlarge",
            "elasticache.cache.m8g.8xlarge",
            "elasticache.cache.m8g.12xlarge",
            "elasticache.cache.m8g.16xlarge",
            "elasticache.cache.r8g.large",
            "elasticache.cache.r8g.xlarge",
            "elasticache.cache.r8g.2xlarge",
            "elasticache.cache.r8g.4xlarge",
            "elasticache.cache.r8g.8xlarge",
            "elasticache.cache.r8g.12xlarge",
            "elasticache.cache.r8g.16xlarge",
            "elasticache.cache.c8gn.large",
            "elasticache.cache.c8gn.xlarge",
            "elasticache.cache.c8gn.2xlarge",
            "elasticache.cache.c8gn.4xlarge",
            "elasticache.cache.c8gn.8xlarge",
            "elasticache.cache.c8gn.12xlarge",
            "elasticache.cache.c8gn.16xlarge"
          ]
        },
        {
          "name": "auto_upgrade_enabled",
          "nullable": false,
          "path": [
            "auto_upgrade_enabled"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "is_public",
          "nullable": false,
          "path": [
            "is_public"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "Only available for Valkey.",
          "name": "eviction_policy",
          "nullable": true,
          "path": [
            "eviction_policy"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "allkeys-lru",
            "noeviction",
            "volatile-lru",
            "allkeys-random",
            "volatile-random",
            "volatile-ttl",
            "allkeys-lfu",
            "volatile-lfu"
          ]
        },
        {
          "name": "uses_hibernation",
          "nullable": false,
          "path": [
            "uses_hibernation"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 60,
          "min": 1,
          "name": "hibernation_timeout",
          "nullable": true,
          "path": [
            "hibernation_timeout"
          ],
          "required": false,
          "kind": "integer"
        }
      ]
    },
    "description": "Update a cache.",
    "method": "PATCH",
    "operationId": "public.caches.update",
    "params": [
      "cache"
    ],
    "path": "/caches/{cache}",
    "query": [],
    "summary": "Update cache",
    "tag": "Caches"
  },
  {
    "body": null,
    "description": "Delete a cache.",
    "method": "DELETE",
    "operationId": "public.caches.destroy",
    "params": [
      "cache"
    ],
    "path": "/caches/{cache}",
    "query": [],
    "summary": "Delete cache",
    "tag": "Caches"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 150000,
          "minLength": 1,
          "name": "command",
          "nullable": false,
          "path": [
            "command"
          ],
          "required": true,
          "kind": "string"
        }
      ]
    },
    "description": "Run a command on the given environment.",
    "method": "POST",
    "operationId": "public.environments.commands.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/commands",
    "query": [],
    "summary": "Run command",
    "tag": "Commands"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "laravel_mysql_84",
            "laravel_mysql_8",
            "aws_rds_mysql_8",
            "aws_rds_postgres_18",
            "neon_serverless_postgres_18",
            "neon_serverless_postgres_17",
            "neon_serverless_postgres_16"
          ]
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "region",
          "nullable": false,
          "path": [
            "region"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "us-east-2",
            "us-east-1",
            "ca-central-1",
            "eu-central-1",
            "eu-west-1",
            "eu-west-2",
            "me-central-1",
            "ap-southeast-1",
            "ap-southeast-2",
            "ap-northeast-1"
          ]
        },
        {
          "description": "Configuration object. Fields vary based on database type. One of: Neon Serverless Postgres, Laravel MySQL, AWS RDS.",
          "name": "config",
          "nullable": false,
          "path": [
            "config"
          ],
          "required": true,
          "example": "{\"cu_min\":0.25,\"cu_max\":0.25,\"suspend_seconds\":1,\"retention_days\":1}",
          "kind": "json"
        },
        {
          "name": "cluster_id",
          "nullable": true,
          "path": [
            "cluster_id"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new database cluster. A default database will also be created and returned on the `databases` relationship.",
    "method": "POST",
    "operationId": "public.databases.clusters.store",
    "params": [],
    "path": "/databases/clusters",
    "query": [],
    "summary": "Create database cluster",
    "tag": "Database Clusters"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "Configuration object. Fields vary based on database type. One of: Neon Serverless Postgres, Laravel MySQL, AWS RDS.",
          "name": "config",
          "nullable": false,
          "path": [
            "config"
          ],
          "required": true,
          "example": "{\"cu_min\":0.25,\"cu_max\":0.25,\"suspend_seconds\":1,\"retention_days\":1}",
          "kind": "json"
        }
      ]
    },
    "description": "Update a database cluster.",
    "method": "PATCH",
    "operationId": "public.databases.clusters.update",
    "params": [
      "database"
    ],
    "path": "/databases/clusters/{database}",
    "query": [],
    "summary": "Update database cluster",
    "tag": "Database Clusters"
  },
  {
    "body": null,
    "description": "Delete a database cluster.",
    "method": "DELETE",
    "operationId": "public.databases.clusters.destroy",
    "params": [
      "database"
    ],
    "path": "/databases/clusters/{database}",
    "query": [],
    "summary": "Delete database cluster",
    "tag": "Database Clusters"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "The name of the new database created from the restore.",
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "description": "The point in time to restore the database to. Must not be used with database_snapshot_id.",
          "format": "date-time",
          "name": "restore_time",
          "nullable": true,
          "path": [
            "restore_time"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "database_snapshot_id",
          "nullable": true,
          "path": [
            "database_snapshot_id"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Restore a database cluster from a point in time or snapshot. Returns the newly created database.",
    "method": "POST",
    "operationId": "public.databases.clusters.restore",
    "params": [
      "database"
    ],
    "path": "/databases/clusters/{database}/restore",
    "query": [],
    "summary": "Create a database restore",
    "tag": "Database Restores"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 100,
          "minLength": 1,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "description",
          "nullable": true,
          "path": [
            "description"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new manual snapshot for a database cluster.",
    "method": "POST",
    "operationId": "public.databases.clusters.snapshots.store",
    "params": [
      "database"
    ],
    "path": "/databases/clusters/{database}/snapshots",
    "query": [],
    "summary": "Create a database snapshot",
    "tag": "Database Snapshots"
  },
  {
    "body": null,
    "description": "Delete a snapshot from a database cluster. Automatic backups cannot be deleted while point-in-time recovery is enabled.",
    "method": "DELETE",
    "operationId": "public.database-snapshots.destroy",
    "params": [
      "databaseSnapshot"
    ],
    "path": "/database-snapshots/{databaseSnapshot}",
    "query": [],
    "summary": "Delete a database snapshot",
    "tag": "Database Snapshots"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new database in a database cluster.",
    "method": "POST",
    "operationId": "public.databases.clusters.databases.store",
    "params": [
      "database"
    ],
    "path": "/databases/clusters/{database}/databases",
    "query": [],
    "summary": "Create a database",
    "tag": "Databases"
  },
  {
    "body": null,
    "description": "Delete a database from a database cluster.",
    "method": "DELETE",
    "operationId": "public.databases.clusters.databases.destroy",
    "params": [
      "database",
      "schema"
    ],
    "path": "/databases/clusters/{database}/databases/{schema}",
    "query": [],
    "summary": "Delete a database",
    "tag": "Databases"
  },
  {
    "body": null,
    "description": "Initiate a deployment for the given environment.",
    "method": "POST",
    "operationId": "public.environments.deployments.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/deployments",
    "query": [],
    "summary": "Initiate deployment",
    "tag": "Deployments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 255,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "name": "www_redirect",
          "nullable": true,
          "path": [
            "www_redirect"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "root_to_www",
            "www_to_root"
          ]
        },
        {
          "description": "Whether to enable a wildcard subdomain (*.example.com) for this domain.",
          "name": "wildcard_enabled",
          "nullable": true,
          "path": [
            "wildcard_enabled"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "Whether to allow downtime during domain verification. When true (flexible), the domain can be pointed directly without pre-verification. When false (uninterrupted), the domain is pre-verified before traffic moves: TXT-based ownership pre-verification for \"none\" and \"dns\" strategies, certificate pre-issuance via DCV CNAMEs for \"dns_proxy\" (Cloudflare does not accept ownership tokens for proxied hostnames).",
          "name": "allow_downtime",
          "nullable": true,
          "path": [
            "allow_downtime"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "The Cloudflare integration strategy. \"none\" uses A records with no Cloudflare integration. \"dns\" uses CNAME records via Cloudflare DNS only. \"dns_proxy\" uses CNAME records with Cloudflare's proxy enabled (Orange cloud).",
          "name": "cloudflare_strategy",
          "nullable": true,
          "path": [
            "cloudflare_strategy"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "dns_proxy",
            "dns",
            "none"
          ]
        },
        {
          "description": "The domain verification method to use. Pre-verification allows domain verification via TXT record before the domain is pointed to the environment. Real-time verification requires the domain to already be pointing to the environment.",
          "name": "verification_method",
          "nullable": true,
          "path": [
            "verification_method"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "pre_verification",
            "real_time"
          ]
        }
      ]
    },
    "description": "Create a new domain for the given environment. After creating the domain, you'll have to add the required DNS records to your DNS provider. This might be a 2-step process, depending on the verification method used. You can check the required DNS records in the response of this endpoint, and you can verify the domain using the \"verify\" query parameter in the \"Get domain\" endpoint.",
    "method": "POST",
    "operationId": "public.environments.domains.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/domains",
    "query": [],
    "summary": "Create domain",
    "tag": "Domains"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "The domain verification method to use. Pre-verification allows domain verification via TXT record before the domain is pointed to the environment. Real-time verification requires the domain to already be pointing to the environment.",
          "name": "verification_method",
          "nullable": false,
          "path": [
            "verification_method"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "pre_verification",
            "real_time"
          ]
        }
      ]
    },
    "description": "Update a specific domain.",
    "method": "PATCH",
    "operationId": "public.domains.update",
    "params": [
      "domain"
    ],
    "path": "/domains/{domain}",
    "query": [],
    "summary": "Update domain",
    "tag": "Domains"
  },
  {
    "body": null,
    "description": "Delete a specific domain.",
    "method": "DELETE",
    "operationId": "public.domains.destroy",
    "params": [
      "domain"
    ],
    "path": "/domains/{domain}",
    "query": [],
    "summary": "Delete domain",
    "tag": "Domains"
  },
  {
    "body": null,
    "description": "Checks whether the DNS records for a given domain have been properly set up.",
    "method": "POST",
    "operationId": "public.domains.verify",
    "params": [
      "domain"
    ],
    "path": "/domains/{domain}/verify",
    "query": [],
    "summary": "Verify a domain",
    "tag": "Domains"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "branch",
          "nullable": false,
          "path": [
            "branch"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 40,
          "minLength": 1,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[A-Za-z0-9 _-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "description": "The identifier of a dedicated cluster to deploy to. Only fill it if your organization has a dedicated cluster and you want to use it for this environment.",
          "name": "cluster_id",
          "nullable": true,
          "path": [
            "cluster_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "description": "The identifier of the edge network the environment should be created in. Only fill it if your organization has a dedicated edge network and you want to use it for this environment. Defaults to the edge network preferred by your organization.",
          "name": "edge_network_id",
          "nullable": true,
          "path": [
            "edge_network_id"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new environment.",
    "method": "POST",
    "operationId": "public.applications.environments.store",
    "params": [
      "application"
    ],
    "path": "/applications/{application}/environments",
    "query": [],
    "summary": "Create environment",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 1,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[A-Za-z0-9 _-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "minLength": 1,
          "name": "slug",
          "nullable": false,
          "path": [
            "slug"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "color",
          "nullable": false,
          "path": [
            "color"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "blue",
            "green",
            "orange",
            "purple",
            "red",
            "yellow",
            "cyan",
            "gray"
          ]
        },
        {
          "name": "branch",
          "nullable": false,
          "path": [
            "branch"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "uses_push_to_deploy",
          "nullable": false,
          "path": [
            "uses_push_to_deploy"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "uses_deploy_hook",
          "nullable": false,
          "path": [
            "uses_deploy_hook"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 60,
          "min": 5,
          "name": "timeout",
          "nullable": false,
          "path": [
            "timeout"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "name": "php_version",
          "nullable": false,
          "path": [
            "php_version"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "8.2:1",
            "8.3:1",
            "8.4:1",
            "8.5:1"
          ]
        },
        {
          "maxLength": 2000,
          "name": "build_command",
          "nullable": true,
          "path": [
            "build_command"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "node_version",
          "nullable": false,
          "path": [
            "node_version"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "20",
            "22",
            "24"
          ]
        },
        {
          "maxLength": 2000,
          "name": "deploy_command",
          "nullable": true,
          "path": [
            "deploy_command"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "uses_vanity_domain",
          "nullable": false,
          "path": [
            "uses_vanity_domain"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "The identifier of the database schema to attach to the environment. Send null or an empty string to detach the database, or skip it entirely to leave it unchanged.",
          "name": "database_schema_id",
          "nullable": true,
          "path": [
            "database_schema_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "description": "The identifier of the cache to attach to the environment. Send null or an empty string to detach the cache, or skip it entirely to leave it unchanged.",
          "name": "cache_id",
          "nullable": true,
          "path": [
            "cache_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "description": "The identifier of the WebSocket application to attach to the environment. Send null or an empty string to detach the WebSocket application, or skip it entirely to leave it unchanged.",
          "name": "websocket_application_id",
          "nullable": true,
          "path": [
            "websocket_application_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "description": "An array of the object storage buckets that should be attached to the environment. Send an emtpy array ([]) to detach all buckets.",
          "name": "filesystem_keys",
          "nullable": false,
          "path": [
            "filesystem_keys"
          ],
          "required": false,
          "example": "[{\"id\":\"value\",\"disk\":\"value\",\"is_default_disk\":true}]",
          "kind": "json"
        },
        {
          "name": "uses_octane",
          "nullable": false,
          "path": [
            "uses_octane"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 60,
          "min": 1,
          "name": "sleep_timeout",
          "nullable": false,
          "path": [
            "sleep_timeout"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "description": "The periodic wake-up interval in minutes for hibernating environments. Send null to disable, or a value between 1 and 10080 (7 days) to enable. Requires hibernation to be enabled.",
          "max": 10080,
          "min": 1,
          "name": "hibernation_wake_up_interval",
          "nullable": true,
          "path": [
            "hibernation_wake_up_interval"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "max": 600,
          "min": 1,
          "name": "shutdown_timeout",
          "nullable": false,
          "path": [
            "shutdown_timeout"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "name": "uses_purge_edge_cache_on_deploy",
          "nullable": false,
          "path": [
            "uses_purge_edge_cache_on_deploy"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "maxLength": 44,
          "minLength": 44,
          "name": "nightwatch_token",
          "nullable": true,
          "path": [
            "nightwatch_token"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "cache_strategy",
          "nullable": false,
          "path": [
            "cache_strategy"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "default",
            "bypass"
          ]
        },
        {
          "name": "response_headers_frame",
          "nullable": false,
          "path": [
            "response_headers_frame"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "deny",
            "sameorigin",
            "all"
          ]
        },
        {
          "name": "response_headers_content_type",
          "nullable": false,
          "path": [
            "response_headers_content_type"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "nosniff",
            "none"
          ]
        },
        {
          "name": "response_headers_robots_tag",
          "nullable": false,
          "path": [
            "response_headers_robots_tag"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "index, follow",
            "noindex, nofollow"
          ]
        },
        {
          "min": 0,
          "name": "response_headers_hsts.max_age",
          "nullable": true,
          "path": [
            "response_headers_hsts",
            "max_age"
          ],
          "required": false,
          "kind": "number"
        },
        {
          "name": "response_headers_hsts.include_subdomains",
          "nullable": false,
          "path": [
            "response_headers_hsts",
            "include_subdomains"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "response_headers_hsts.preload",
          "nullable": false,
          "path": [
            "response_headers_hsts",
            "preload"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "firewall_block_path",
          "nullable": false,
          "path": [
            "firewall_block_path"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "firewall_browser_integrity_check",
          "nullable": false,
          "path": [
            "firewall_browser_integrity_check"
          ],
          "required": false,
          "kind": "boolean"
        }
      ]
    },
    "description": "Update an environment.",
    "method": "PATCH",
    "operationId": "public.environments.update",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}",
    "query": [],
    "summary": "Update environment",
    "tag": "Environments"
  },
  {
    "body": null,
    "description": "Delete an environment.",
    "method": "DELETE",
    "operationId": "public.environments.destroy",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}",
    "query": [],
    "summary": "Delete environment",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "Pass true to redeploy the environment with the same commit as the latest deployment. Otherwise, the latest commit will be used.",
          "name": "redeploy",
          "nullable": true,
          "path": [
            "redeploy"
          ],
          "required": false,
          "kind": "boolean"
        }
      ]
    },
    "description": "Start an environment and trigger a deployment.",
    "method": "POST",
    "operationId": "public.environments.start",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/start",
    "query": [],
    "summary": "Start environment",
    "tag": "Environments"
  },
  {
    "body": null,
    "description": "Stop an environment and cancel any in-progress deployment.",
    "method": "POST",
    "operationId": "public.environments.stop",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/stop",
    "query": [],
    "summary": "Stop environment",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "A single path to purge, resolved against every hostname the environment is served from.",
          "maxLength": 2048,
          "name": "path",
          "nullable": true,
          "path": [
            "path"
          ],
          "required": false,
          "example": "/blog/hello-world",
          "kind": "string"
        },
        {
          "description": "A path prefix to purge, resolved against every hostname the environment is served from.",
          "maxLength": 2048,
          "name": "prefix",
          "nullable": true,
          "path": [
            "prefix"
          ],
          "required": false,
          "example": "/blog/",
          "kind": "string"
        },
        {
          "description": "A `Cache-Tag` value to purge. Requires the environment to use a dedicated edge network.",
          "maxLength": 1024,
          "name": "tag",
          "nullable": true,
          "path": [
            "tag"
          ],
          "required": false,
          "example": "blog-posts",
          "kind": "string"
        }
      ]
    },
    "description": "Purge the edge cache for all domains associated with the environment.\n\nBy default everything cached for the environment is purged. Optionally provide\na `path`, `prefix`, or `tag` to purge a subset of the cache. Only one of\nthese may be provided per request.",
    "method": "POST",
    "operationId": "public.environments.purge-edge-cache",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/purge-edge-cache",
    "query": [],
    "summary": "Purge edge cache",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 100,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        }
      ]
    },
    "description": "Update the vanity domain for the environment. May only be done once every 30 minutes.",
    "method": "PUT",
    "operationId": "public.environments.vanity-domain.update",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/vanity-domain",
    "query": [],
    "summary": "Update vanity domain",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "description": "When set to 'append', variables are added to the end without checking for duplicates.\nWhen set to 'set', variables with matching keys are updated; otherwise they are added.",
          "name": "method",
          "nullable": false,
          "path": [
            "method"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "append",
            "set"
          ]
        },
        {
          "name": "variables",
          "nullable": false,
          "path": [
            "variables"
          ],
          "required": true,
          "example": "[{\"key\":\"value\",\"value\":\"value\"}]",
          "kind": "json"
        }
      ]
    },
    "description": "Add environment variables to an environment.",
    "method": "POST",
    "operationId": "public.environments.variables.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/variables",
    "query": [],
    "summary": "Add environment variables",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "keys",
          "nullable": false,
          "path": [
            "keys"
          ],
          "required": true,
          "kind": "string-list"
        }
      ]
    },
    "description": "Remove specific environment variables by key name. This operation is atomic: if any of the specified keys do not exist, no variables will be deleted and an error will be returned indicating which keys were missing.",
    "method": "POST",
    "operationId": "public.environments.variables.destroy",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/variables/delete",
    "query": [],
    "summary": "Delete environment variables",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "secrets",
          "nullable": false,
          "path": [
            "secrets"
          ],
          "required": true,
          "kind": "string-list"
        }
      ]
    },
    "description": "Attach one or more of the organization's secrets to an environment. Secrets that are already\nattached to the environment are ignored.",
    "method": "POST",
    "operationId": "public.environments.secrets.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/secrets",
    "query": [],
    "summary": "Attach secrets to environment",
    "tag": "Environments"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "service",
            "managed_queue"
          ]
        },
        {
          "name": "size",
          "nullable": false,
          "path": [
            "size"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "flex-512mb",
            "flex-1gb",
            "flex-2gb",
            "flex.c-1vcpu-256mb",
            "flex.g-1vcpu-512mb",
            "flex.m-1vcpu-1gb",
            "flex.c-2vcpu-512mb",
            "flex.g-2vcpu-1gb",
            "flex.m-2vcpu-2gb",
            "flex.c-4vcpu-1gb",
            "flex.g-4vcpu-2gb",
            "flex.m-4vcpu-4gb",
            "flex.c-8vcpu-2gb",
            "flex.g-8vcpu-4gb",
            "flex.m-8vcpu-8gb",
            "pro.c-1vcpu-1gb",
            "pro.g-1vcpu-2gb",
            "pro.m-1vcpu-4gb",
            "pro.c-2vcpu-2gb",
            "pro.g-2vcpu-4gb",
            "pro.m-2vcpu-8gb",
            "pro.c-4vcpu-4gb",
            "pro.g-4vcpu-8gb",
            "pro.m-4vcpu-16gb",
            "pro.c-8vcpu-8gb",
            "pro.g-8vcpu-16gb",
            "pro.m-8vcpu-32gb",
            "dedicated.c-1vcpu-2gb",
            "dedicated.g-1vcpu-4gb",
            "dedicated.m-1vcpu-8gb",
            "dedicated.c-2vcpu-4gb",
            "dedicated.g-2vcpu-8gb",
            "dedicated.m-2vcpu-16gb",
            "dedicated.c-4vcpu-8gb",
            "dedicated.g-4vcpu-16gb",
            "dedicated.m-4vcpu-32gb",
            "dedicated.c-8vcpu-16gb",
            "dedicated.g-8vcpu-32gb",
            "dedicated.m-8vcpu-64gb",
            "mq-pro-256mb",
            "mq-pro-512mb",
            "mq-pro-1gb",
            "mq-pro-2gb",
            "mq-pro-4gb",
            "mq-pro-8gb",
            "mq-dedicated-256mb",
            "mq-dedicated-512mb",
            "mq-dedicated-1gb",
            "mq-dedicated-2gb",
            "mq-dedicated-4gb",
            "mq-dedicated-8gb",
            "mq-dedicated-16gb",
            "mq.flex.256mb",
            "mq.flex.512mb",
            "mq.flex.1gb",
            "mq.flex.2gb",
            "mq.pro.256mb",
            "mq.pro.512mb",
            "mq.pro.1gb",
            "mq.pro.2gb",
            "mq.pro.4gb",
            "mq.pro.8gb",
            "mq.dedicated.flex.256mb",
            "mq.dedicated.flex.512mb",
            "mq.dedicated.flex.1gb",
            "mq.dedicated.flex.2gb",
            "mq.dedicated.pro.256mb",
            "mq.dedicated.pro.512mb",
            "mq.dedicated.pro.1gb",
            "mq.dedicated.pro.2gb",
            "mq.dedicated.pro.4gb",
            "mq.dedicated.pro.8gb",
            "mq.dedicated.pro.16gb"
          ]
        },
        {
          "name": "scaling_type",
          "nullable": false,
          "path": [
            "scaling_type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "none",
            "custom",
            "auto"
          ]
        },
        {
          "description": "The maximum number of replicas the instance can scale to. Only applicable to the `custom` scaling type, and rejected when used with `auto`.",
          "name": "max_replicas",
          "nullable": false,
          "path": [
            "max_replicas"
          ],
          "required": false,
          "example": "10",
          "kind": "integer"
        },
        {
          "description": "The minimum number of replicas the instance runs. Only applicable to the `custom` scaling type, and rejected when used with `auto`. Not applicable to managed queues, which always scale to zero when idle.",
          "name": "min_replicas",
          "nullable": false,
          "path": [
            "min_replicas"
          ],
          "required": true,
          "example": "1",
          "kind": "integer"
        },
        {
          "name": "uses_scheduler",
          "nullable": false,
          "path": [
            "uses_scheduler"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "Whether worker replicas scale to zero alongside the app cluster, waking when they receive traffic. Only applicable to worker (service) instances.",
          "name": "sleep_with_app",
          "nullable": false,
          "path": [
            "sleep_with_app"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 95,
          "min": 50,
          "name": "scaling_cpu_threshold_percentage",
          "nullable": true,
          "path": [
            "scaling_cpu_threshold_percentage"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "max": 95,
          "min": 50,
          "name": "scaling_memory_threshold_percentage",
          "nullable": true,
          "path": [
            "scaling_memory_threshold_percentage"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "description": "How long a message stays hidden from other workers while one is processing it. Only available when the\norganization has the advanced managed queues entitlement; ignored otherwise, and the platform manages it.",
          "name": "visibility_timeout",
          "nullable": true,
          "path": [
            "visibility_timeout"
          ],
          "required": true,
          "example": "180",
          "kind": "integer"
        },
        {
          "description": "The time a worker has to finish its current job before being forcefully shut down. Only available when the\norganization has the advanced managed queues entitlement; ignored otherwise, and the platform manages it.",
          "name": "shutdown_timeout",
          "nullable": true,
          "path": [
            "shutdown_timeout"
          ],
          "required": true,
          "example": "90",
          "kind": "integer"
        },
        {
          "name": "background_processes",
          "nullable": false,
          "path": [
            "background_processes"
          ],
          "required": false,
          "example": "[{\"type\":\"worker\",\"processes\":1,\"command\":\"php artisan my:command\",\"config\":{\"connection\":\"redis\",\"queue\":\"default,emails\",\"tries\":3,\"backoff\":30,\"sleep\":3,\"rest\":0,\"timeout\":60,\"force\":false}}]",
          "kind": "json"
        }
      ]
    },
    "description": "Create a new instance for an environment.",
    "method": "POST",
    "operationId": "public.environments.instances.store",
    "params": [
      "environment"
    ],
    "path": "/environments/{environment}/instances",
    "query": [],
    "summary": "Create instance",
    "tag": "Instances"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "name": "size",
          "nullable": false,
          "path": [
            "size"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "flex-512mb",
            "flex-1gb",
            "flex-2gb",
            "flex.c-1vcpu-256mb",
            "flex.g-1vcpu-512mb",
            "flex.m-1vcpu-1gb",
            "flex.c-2vcpu-512mb",
            "flex.g-2vcpu-1gb",
            "flex.m-2vcpu-2gb",
            "flex.c-4vcpu-1gb",
            "flex.g-4vcpu-2gb",
            "flex.m-4vcpu-4gb",
            "flex.c-8vcpu-2gb",
            "flex.g-8vcpu-4gb",
            "flex.m-8vcpu-8gb",
            "pro.c-1vcpu-1gb",
            "pro.g-1vcpu-2gb",
            "pro.m-1vcpu-4gb",
            "pro.c-2vcpu-2gb",
            "pro.g-2vcpu-4gb",
            "pro.m-2vcpu-8gb",
            "pro.c-4vcpu-4gb",
            "pro.g-4vcpu-8gb",
            "pro.m-4vcpu-16gb",
            "pro.c-8vcpu-8gb",
            "pro.g-8vcpu-16gb",
            "pro.m-8vcpu-32gb",
            "dedicated.c-1vcpu-2gb",
            "dedicated.g-1vcpu-4gb",
            "dedicated.m-1vcpu-8gb",
            "dedicated.c-2vcpu-4gb",
            "dedicated.g-2vcpu-8gb",
            "dedicated.m-2vcpu-16gb",
            "dedicated.c-4vcpu-8gb",
            "dedicated.g-4vcpu-16gb",
            "dedicated.m-4vcpu-32gb",
            "dedicated.c-8vcpu-16gb",
            "dedicated.g-8vcpu-32gb",
            "dedicated.m-8vcpu-64gb",
            "mq-pro-256mb",
            "mq-pro-512mb",
            "mq-pro-1gb",
            "mq-pro-2gb",
            "mq-pro-4gb",
            "mq-pro-8gb",
            "mq-dedicated-256mb",
            "mq-dedicated-512mb",
            "mq-dedicated-1gb",
            "mq-dedicated-2gb",
            "mq-dedicated-4gb",
            "mq-dedicated-8gb",
            "mq-dedicated-16gb",
            "mq.flex.256mb",
            "mq.flex.512mb",
            "mq.flex.1gb",
            "mq.flex.2gb",
            "mq.pro.256mb",
            "mq.pro.512mb",
            "mq.pro.1gb",
            "mq.pro.2gb",
            "mq.pro.4gb",
            "mq.pro.8gb",
            "mq.dedicated.flex.256mb",
            "mq.dedicated.flex.512mb",
            "mq.dedicated.flex.1gb",
            "mq.dedicated.flex.2gb",
            "mq.dedicated.pro.256mb",
            "mq.dedicated.pro.512mb",
            "mq.dedicated.pro.1gb",
            "mq.dedicated.pro.2gb",
            "mq.dedicated.pro.4gb",
            "mq.dedicated.pro.8gb",
            "mq.dedicated.pro.16gb"
          ]
        },
        {
          "name": "scaling_type",
          "nullable": false,
          "path": [
            "scaling_type"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "none",
            "custom",
            "auto"
          ]
        },
        {
          "description": "The maximum number of replicas the instance can scale to. Only applicable to the `custom` scaling type, and rejected when used with `auto`.",
          "name": "max_replicas",
          "nullable": false,
          "path": [
            "max_replicas"
          ],
          "required": false,
          "example": "10",
          "kind": "integer"
        },
        {
          "description": "The minimum number of replicas the instance runs. Only applicable to the `custom` scaling type, and rejected when used with `auto`.",
          "name": "min_replicas",
          "nullable": false,
          "path": [
            "min_replicas"
          ],
          "required": false,
          "example": "1",
          "kind": "integer"
        },
        {
          "description": "Number of minutes before the application hibernates. Set to null to disable hibernation, or omit it to avoid changing the hibernation settings.\nTakes precedence over the deprecated uses_sleep_mode and sleep_timeout fields.",
          "name": "hibernation_timeout",
          "nullable": true,
          "path": [
            "hibernation_timeout"
          ],
          "required": false,
          "example": "5",
          "kind": "integer"
        },
        {
          "description": "Use hibernation_timeout instead.",
          "name": "uses_sleep_mode",
          "nullable": false,
          "path": [
            "uses_sleep_mode"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "Use hibernation_timeout instead.",
          "max": 60,
          "min": 1,
          "name": "sleep_timeout",
          "nullable": false,
          "path": [
            "sleep_timeout"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "name": "uses_scheduler",
          "nullable": false,
          "path": [
            "uses_scheduler"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "description": "Whether worker replicas scale to zero alongside the app cluster, waking when they receive traffic. Only applicable to worker (service) instances.",
          "name": "sleep_with_app",
          "nullable": false,
          "path": [
            "sleep_with_app"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "uses_octane",
          "nullable": false,
          "path": [
            "uses_octane"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "name": "uses_inertia_ssr",
          "nullable": false,
          "path": [
            "uses_inertia_ssr"
          ],
          "required": false,
          "kind": "boolean"
        },
        {
          "max": 95,
          "min": 50,
          "name": "scaling_cpu_threshold_percentage",
          "nullable": true,
          "path": [
            "scaling_cpu_threshold_percentage"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "max": 95,
          "min": 50,
          "name": "scaling_memory_threshold_percentage",
          "nullable": true,
          "path": [
            "scaling_memory_threshold_percentage"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "description": "How long a message stays hidden from other workers while one is processing it. Only available when the\norganization has the advanced managed queues entitlement; ignored otherwise, and the platform manages it.",
          "name": "visibility_timeout",
          "nullable": true,
          "path": [
            "visibility_timeout"
          ],
          "required": false,
          "example": "180",
          "kind": "integer"
        },
        {
          "description": "The time a worker has to finish its current job before being forcefully shut down. Only available when the\norganization has the advanced managed queues entitlement; ignored otherwise, and the platform manages it.",
          "name": "shutdown_timeout",
          "nullable": true,
          "path": [
            "shutdown_timeout"
          ],
          "required": false,
          "example": "90",
          "kind": "integer"
        }
      ]
    },
    "description": "Update an instance.",
    "method": "PATCH",
    "operationId": "public.instances.update",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}",
    "query": [],
    "summary": "Update instance",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Delete an instance.",
    "method": "DELETE",
    "operationId": "public.instances.destroy",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}",
    "query": [],
    "summary": "Delete instance",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Stop dispatching jobs to the queue's workers; queued messages are retained until it is resumed.",
    "method": "POST",
    "operationId": "public.instances.pause",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/pause",
    "query": [],
    "summary": "Pause a managed queue",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Resume dispatching jobs to the queue's workers after it was paused.",
    "method": "POST",
    "operationId": "public.instances.resume",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/resume",
    "query": [],
    "summary": "Resume a managed queue",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Permanently delete all messages currently in the queue. This cannot be undone.",
    "method": "POST",
    "operationId": "public.instances.purge",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/purge",
    "query": [],
    "summary": "Purge a managed queue",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Make this queue the environment's default, used when a job does not specify a queue.",
    "method": "POST",
    "operationId": "public.instances.default",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/default",
    "query": [],
    "summary": "Set the default managed queue",
    "tag": "Instances"
  },
  {
    "body": null,
    "method": "DELETE",
    "operationId": "public.instances.failed-jobs.destroy-many",
    "params": [
      "instance"
    ],
    "path": "/instances/{instance}/failed-jobs",
    "query": [
      {
        "name": "jobIds",
        "nullable": false,
        "path": [
          "jobIds"
        ],
        "required": false,
        "kind": "string"
      },
      {
        "name": "failedBefore",
        "nullable": false,
        "path": [
          "failedBefore"
        ],
        "required": false,
        "kind": "string"
      }
    ],
    "summary": "Delete managed queue failed jobs",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Re-queue a failed job so it is processed again.",
    "method": "POST",
    "operationId": "public.instances.failed-jobs.retry",
    "params": [
      "instance",
      "jobId"
    ],
    "path": "/instances/{instance}/failed-jobs/{jobId}/retry",
    "query": [],
    "summary": "Retry a managed queue failed job",
    "tag": "Instances"
  },
  {
    "body": null,
    "description": "Permanently remove a failed job from the given managed queue.",
    "method": "DELETE",
    "operationId": "public.instances.failed-jobs.destroy",
    "params": [
      "instance",
      "jobId"
    ],
    "path": "/instances/{instance}/failed-jobs/{jobId}",
    "query": [],
    "summary": "Delete a managed queue failed job",
    "tag": "Instances"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "visibility",
          "nullable": false,
          "path": [
            "visibility"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "private",
            "public"
          ]
        },
        {
          "name": "jurisdiction",
          "nullable": false,
          "path": [
            "jurisdiction"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "default",
            "eu"
          ]
        },
        {
          "description": "This field is deprecated and will be removed May 17th, 2026. Please use `cors_settings.allowed_origins` instead.",
          "name": "allowed_origins",
          "nullable": true,
          "path": [
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.allowed_origins",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.allowed_methods",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_methods"
          ],
          "required": false,
          "kind": "string-list",
          "options": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "HEAD"
          ]
        },
        {
          "name": "cors_settings.allowed_headers",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_headers"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.expose_headers",
          "nullable": true,
          "path": [
            "cors_settings",
            "expose_headers"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "min": 1,
          "name": "cors_settings.max_age_seconds",
          "nullable": true,
          "path": [
            "cors_settings",
            "max_age_seconds"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "key_name",
          "nullable": false,
          "path": [
            "key_name"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "name": "key_permission",
          "nullable": false,
          "path": [
            "key_permission"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "read_write",
            "read_only"
          ]
        }
      ]
    },
    "description": "Create a new object storage bucket with an initial key.",
    "method": "POST",
    "operationId": "public.buckets.store",
    "params": [],
    "path": "/buckets",
    "query": [],
    "summary": "Create object storage bucket",
    "tag": "Object Storage Buckets"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "name": "visibility",
          "nullable": false,
          "path": [
            "visibility"
          ],
          "required": false,
          "kind": "enum",
          "options": [
            "private",
            "public"
          ]
        },
        {
          "description": "This field is deprecated and will be removed May 17th, 2026. Please use `cors_settings.allowed_origins` instead.",
          "name": "allowed_origins",
          "nullable": true,
          "path": [
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.allowed_origins",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.allowed_methods",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_methods"
          ],
          "required": false,
          "kind": "string-list",
          "options": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "HEAD"
          ]
        },
        {
          "name": "cors_settings.allowed_headers",
          "nullable": true,
          "path": [
            "cors_settings",
            "allowed_headers"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "name": "cors_settings.expose_headers",
          "nullable": true,
          "path": [
            "cors_settings",
            "expose_headers"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "min": 1,
          "name": "cors_settings.max_age_seconds",
          "nullable": true,
          "path": [
            "cors_settings",
            "max_age_seconds"
          ],
          "required": false,
          "kind": "integer"
        }
      ]
    },
    "description": "Update an object storage bucket.",
    "method": "PATCH",
    "operationId": "public.buckets.update",
    "params": [
      "filesystem"
    ],
    "path": "/buckets/{filesystem}",
    "query": [],
    "summary": "Update object storage bucket",
    "tag": "Object Storage Buckets"
  },
  {
    "body": null,
    "description": "Delete an object storage bucket.",
    "method": "DELETE",
    "operationId": "public.buckets.destroy",
    "params": [
      "filesystem"
    ],
    "path": "/buckets/{filesystem}",
    "query": [],
    "summary": "Delete object storage bucket",
    "tag": "Object Storage Buckets"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "key_pair_id",
          "nullable": false,
          "path": [
            "key_pair_id"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 255,
          "name": "key",
          "nullable": false,
          "path": [
            "key"
          ],
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$",
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 7500,
          "name": "value",
          "nullable": false,
          "path": [
            "value"
          ],
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 500,
          "name": "notes",
          "nullable": true,
          "path": [
            "notes"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Create a new secret for the authenticated organization.\n\nThe value must be sealed with the public key of the submitted key pair, both of which are\nreturned by the secrets public key endpoint, before it is submitted.",
    "method": "POST",
    "operationId": "public.secrets.store",
    "params": [],
    "path": "/secrets",
    "query": [],
    "summary": "Create secret",
    "tag": "Secrets"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "name": "key_pair_id",
          "nullable": false,
          "path": [
            "key_pair_id"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "maxLength": 255,
          "name": "key",
          "nullable": false,
          "path": [
            "key"
          ],
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$",
          "required": true,
          "kind": "string"
        },
        {
          "maxLength": 7500,
          "name": "value",
          "nullable": true,
          "path": [
            "value"
          ],
          "required": false,
          "kind": "string"
        },
        {
          "maxLength": 500,
          "name": "notes",
          "nullable": true,
          "path": [
            "notes"
          ],
          "required": false,
          "kind": "string"
        }
      ]
    },
    "description": "Update a secret. A new value must be sealed with the public key of the submitted key pair\nbefore it is submitted.",
    "method": "PATCH",
    "operationId": "public.secrets.update",
    "params": [
      "secret"
    ],
    "path": "/secrets/{secret}",
    "query": [],
    "summary": "Update secret",
    "tag": "Secrets"
  },
  {
    "body": null,
    "description": "Delete a secret and detach it from every environment it is attached to.",
    "method": "DELETE",
    "operationId": "public.secrets.destroy",
    "params": [
      "secret"
    ],
    "path": "/secrets/{secret}",
    "query": [],
    "summary": "Delete secret",
    "tag": "Secrets"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "allowed_origins",
          "nullable": true,
          "path": [
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "max": 60,
          "min": 1,
          "name": "ping_interval",
          "nullable": false,
          "path": [
            "ping_interval"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "max": 60,
          "min": 1,
          "name": "activity_timeout",
          "nullable": false,
          "path": [
            "activity_timeout"
          ],
          "required": false,
          "kind": "integer"
        }
      ]
    },
    "description": "Create a new application for a WebSocket cluster.",
    "method": "POST",
    "operationId": "public.websocket-servers.applications.store",
    "params": [
      "websocketServer"
    ],
    "path": "/websocket-servers/{websocketServer}/applications",
    "query": [],
    "summary": "Create WebSocket application",
    "tag": "WebSocket Applications"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "name": "allowed_origins",
          "nullable": false,
          "path": [
            "allowed_origins"
          ],
          "required": false,
          "kind": "string-list"
        },
        {
          "max": 60,
          "min": 1,
          "name": "ping_interval",
          "nullable": false,
          "path": [
            "ping_interval"
          ],
          "required": false,
          "kind": "integer"
        },
        {
          "max": 60,
          "min": 1,
          "name": "activity_timeout",
          "nullable": false,
          "path": [
            "activity_timeout"
          ],
          "required": false,
          "kind": "integer"
        }
      ]
    },
    "description": "Update a WebSocket application.",
    "method": "PATCH",
    "operationId": "public.websocket-applications.update",
    "params": [
      "websocketApplication"
    ],
    "path": "/websocket-applications/{websocketApplication}",
    "query": [],
    "summary": "Update WebSocket application",
    "tag": "WebSocket Applications"
  },
  {
    "body": null,
    "description": "Delete a WebSocket application.",
    "method": "DELETE",
    "operationId": "public.websocket-applications.destroy",
    "params": [
      "websocketApplication"
    ],
    "path": "/websocket-applications/{websocketApplication}",
    "query": [],
    "summary": "Delete WebSocket application",
    "tag": "WebSocket Applications"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": true,
          "kind": "string"
        },
        {
          "name": "type",
          "nullable": false,
          "path": [
            "type"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "reverb"
          ]
        },
        {
          "name": "region",
          "nullable": false,
          "path": [
            "region"
          ],
          "required": true,
          "kind": "enum",
          "options": [
            "us-east-2",
            "us-east-1",
            "ca-central-1",
            "eu-central-1",
            "eu-west-1",
            "eu-west-2",
            "me-central-1",
            "ap-southeast-1",
            "ap-southeast-2",
            "ap-northeast-1"
          ]
        },
        {
          "name": "max_connections",
          "nullable": false,
          "path": [
            "max_connections"
          ],
          "required": true,
          "kind": "integer"
        }
      ]
    },
    "description": "Create a new WebSocket cluster with a default application.",
    "method": "POST",
    "operationId": "public.websocket-servers.store",
    "params": [],
    "path": "/websocket-servers",
    "query": [],
    "summary": "Create WebSocket cluster",
    "tag": "WebSocket Clusters"
  },
  {
    "body": {
      "contentType": "json",
      "fields": [
        {
          "maxLength": 40,
          "minLength": 3,
          "name": "name",
          "nullable": false,
          "path": [
            "name"
          ],
          "pattern": "^[a-z0-9_-]+$",
          "required": false,
          "kind": "string"
        },
        {
          "description": "The number of maximum connections allowed for the WebSocket server. If passed, the connection distribution strategy will be set to EVENLY.",
          "name": "max_connections",
          "nullable": false,
          "path": [
            "max_connections"
          ],
          "required": false,
          "kind": "enum",
          "numeric": true,
          "options": [
            "100",
            "200",
            "500",
            "2000",
            "5000",
            "10000"
          ]
        }
      ]
    },
    "description": "Update a WebSocket cluster.",
    "method": "PATCH",
    "operationId": "public.websocket-servers.update",
    "params": [
      "websocketServer"
    ],
    "path": "/websocket-servers/{websocketServer}",
    "query": [],
    "summary": "Update WebSocket cluster",
    "tag": "WebSocket Clusters"
  },
  {
    "body": null,
    "description": "Delete a WebSocket cluster and all its applications.",
    "method": "DELETE",
    "operationId": "public.websocket-servers.destroy",
    "params": [
      "websocketServer"
    ],
    "path": "/websocket-servers/{websocketServer}",
    "query": [],
    "summary": "Delete WebSocket cluster",
    "tag": "WebSocket Clusters"
  }
];
